engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  method-complexity:
    enabled: false
  method-lines:
    config:
      threshold: 100
ratings:
  paths:
  - "**.js"
exclude_patterns:
- "**.spec.js"
